#! /usr/bin/env python
#FileName=""
#InFile = open(FileName, 'rU')
seq= "GGTTTCCGATGGCACCTGTGTCAAGGTCTTCCAACAACTCCGGGTCTTCCAGCGACTTCAAGTCTTCCAATAATCTCAAGGTCTTCCAGATAATCCTGAGCTTCCAGAAAATCCACATCT"
mer ="gtctTcca"
output = []
mer = mer.upper()
L=len(mer)
i=0
for i in range(len(seq)):
    t = 0
    errors = 0
    #This if statement assures that we do not go off the end of the string
    if (len(seq)-i) > L:
    # Loops through letter-by-letter and allows for one mismatch. 
    # We could make this a user command (how many mismatches do you want to allow?)
        for t in range(L):
            if seq[i+t] != mer[t]:
                errors += 1
        if errors < 2:
            output.append(i)
print(output)
 
