#! /usr/bin/env python
#FileName=""
#InFile = open(FileName, 'rU')
seqR = "GGTTTCCGATGGCACCTGTGTCAAGGTCTTCCAACAACTCCGGGTCTTCCAGCGACTTCAAGTCTTCCAATAATCTCAAGGTCTTCCAGATAATCCTGAGCTTCCAGAAAATCCACATCT"
seqP = "GGTTTCCGATGGCCCCTGTGTCAAGGTCTTCCAACAACTCCGGGTCTTCCAGCGACTTCAAGTCTTCCAATAATCTCAAGGTCTTCCAGATAATCCTGAGCTTCCAGAAAATCCACATCT"
seqD = "GGTTTCCGATGGCATCTGTGTCAAGGTCTTCCAACAACTCCGGGTCTTCCAGCGACTTCAAGTCTTCCAATAATCTCAAGGTCTTCCAGATAATCCTGAGCTTCCAGAAAATCCACATCT"
mer ="gtctTcca"
PS = []
DS = []
PN = []
DN = []
mer = mer.upper()
L=len(mer)
i=0
for i in range(len(seqR)):
    if seqR[i] != seqP[i]:
        PS.append(i)
    if seqR[i] != seqD[i]:
        DS.append(i)
    t = 0
    errorsPN = 0
    errorsDN = 0
    #This if statement assures that we do not go off the end of the string
    if (len(seqR)-i) > L:
        # Loops through letter-by-letter and allows for one mismatch. 
        # We could make this a user command (how many mismatches do you want to allow?)
        for t in range(L):
            if seqP[i+t] != mer[t]:
                errorsPN += 1
        for t in range(L):
            if seqD[i+t] != mer[t]:
                errorsDN += 1
        if errorsPN < 2:
            PN.append(i)
        if errorsDN < 2:
            DN.append(i)


print(PS)
print(DS)
print(PN)
print(DN)
